import { Router } from 'express';
import { emailRoutes } from './emailRoutes.js';
import { authRoutes } from './authRoutes.js';
import { tableRoutes } from './tableRoutes.js';
import { settingsRoutes } from './settingsRoutes.js';
import { categoriesRoutes } from './categoriesRoutes.js';
import { bannersRoutes } from './bannersRoutes.js';
import { deliveryOptionsRoutes } from './deliveryOptionsRoutes.js';
import { emailTemplatesRoutes } from './emailTemplatesRoutes.js';
import { productsRoutes } from './productsRoutes.js';
import { ordersRoutes } from './ordersRoutes.js';
import { tasksRoutes } from './tasksRoutes.js';
import { employeesRoutes } from './employeesRoutes.js';
import { attendanceRoutes } from './attendanceRoutes.js';
import { expensesRoutes } from './expensesRoutes.js';
import { rolesRoutes } from './rolesRoutes.js';
import { adminRoutes } from './adminRoutes.js';
import { orderChatsRoutes } from './orderChatsRoutes.js';
import { chatRoutes } from './chatRoutes.js';
import { uploadRoutes } from './uploadRoutes.js';
import { customersRoutes } from './customersRoutes.js';
import { balanceInventoryRoutes } from './balanceInventoryRoutes.js';
import { authMiddleware } from '../middleware/authMiddleware.js';

export const apiRouter = Router();

apiRouter.use(authMiddleware);
apiRouter.use(emailRoutes);
apiRouter.use(authRoutes);
apiRouter.use(settingsRoutes);
apiRouter.use(categoriesRoutes);
apiRouter.use(bannersRoutes);
apiRouter.use(deliveryOptionsRoutes);
apiRouter.use(emailTemplatesRoutes);
apiRouter.use(productsRoutes);
apiRouter.use(ordersRoutes);
apiRouter.use(customersRoutes);
apiRouter.use(tasksRoutes);
apiRouter.use(employeesRoutes);
apiRouter.use(attendanceRoutes);
apiRouter.use(expensesRoutes);
apiRouter.use(rolesRoutes);
apiRouter.use(adminRoutes);
apiRouter.use(orderChatsRoutes);
apiRouter.use(chatRoutes);
apiRouter.use(uploadRoutes);
apiRouter.use(tableRoutes);
apiRouter.use(balanceInventoryRoutes);
